// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Sentiment_Analytics_CoursesML.Model
{
    public class ModelInput
    {
        [ColumnName("sentiment"), LoadColumn(0)]
        public string Sentiment { get; set; }


        [ColumnName("sentimentText"), LoadColumn(1)]
        public string SentimentText { get; set; }

        public double Point { get; set; }

        public string Percent { get; set; }

        public string Theme { get; set; }
    }
}
